# Generated by Django 4.1.5 on 2023-02-01 13:38

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pais",
            field=django_countries.fields.CountryField(default="EC", max_length=2),
            preserve_default=False,
        ),
    ]
