# Generated by Django 4.1.5 on 2023-02-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust_app", "0002_alter_company_country_alter_company_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(upload_to="logos/"),
        ),
    ]
