# Generated by Django 4.1.5 on 2023-02-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trust_app", "0003_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rate",
            field=models.IntegerField(
                choices=[
                    (1, "1 stars"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                default=5,
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="website",
            field=models.URLField(verbose_name="Sitio Web"),
        ),
    ]
